# Generated by Django 4.2 on 2023-05-03 01:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reserve_quantity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'medication',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('village_prefix', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('local_name', models.CharField(
                    blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('travelling_time_to_village', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(
                    default=django.utils.timezone.now)),
                ('drug_allergy', models.TextField(default='None')),
                ('parent', models.IntegerField(blank=True, null=True)),
                ('face_encodings', models.CharField(
                    blank=True, max_length=3000, null=True)),
                ('picture', models.ImageField(upload_to='static/images')),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.patient')),
            ],
            options={
                'db_table': 'visits',
            },
        ),
        migrations.CreateModel(
            name='PostReferral',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorder', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('visit', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.visit')),
            ],
            options={
                'db_table': 'postreferrals',
            },
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fg_value', models.BinaryField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('fg_image', models.BinaryField(blank=True, null=True)),
                ('patient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='clinicmodels.patient')),
            ],
            options={
                'db_table': 'fingerprints',
            },
        ),
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('problems', models.TextField(blank=True, null=True)),
                ('referrals', models.TextField(blank=True, null=True)),
                ('chronic_referral', models.BooleanField(blank=True, null=True)),
                ('addendum', models.TextField(blank=True, null=True)),
                ('addendum_time', models.DateTimeField(blank=True, null=True)),
                ('addendum_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='doctor_addendum', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='doctor_create', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.visit')),
            ],
            options={
                'db_table': 'consults',
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('systolic', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('temperature', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('hiv_positive', models.BooleanField(default=False)),
                ('ptb_positive', models.BooleanField(default=False)),
                ('hepc_positive', models.BooleanField(default=False)),
                ('heart_rate', models.IntegerField(default=0)),
                ('visit', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.visit')),
                ('blood_glucose', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('cataracts_scale', models.IntegerField(default=0, validators=[
                 django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('eye_pressure', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('hemocue_count', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('left_eye_degree', models.IntegerField(default=0)),
                ('right_eye_degree', models.IntegerField(default=0)),
                ('urine_test', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vitals',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.medication')),
                ('visit', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.visit')),
                ('order_status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]