# Generated by Django 2.2.4 on 2023-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0002_auto_20190903_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='face_encodings',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
