# Generated by Django 2.2.4 on 2023-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0003_auto_20230314_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='face_encodings',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
