# Generated by Django 4.2 on 2023-05-05 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0008_remove_vitals_cataracts_scale_vitals_cataracts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='visit',
        ),
        migrations.AddField(
            model_name='order',
            name='consult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicmodels.consult'),
        ),
    ]