# Generated by Django 4.2 on 2023-12-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0009_remove_order_visit_order_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='diabetes_mellitus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
