# Generated by Django 4.2 on 2023-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0010_vitals_diabetes_mellitus_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='left_eye_degree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='right_eye_degree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
