# Generated by Django 4.2 on 2023-12-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0013_vitals_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='diabetes_mellitus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
