# Generated by Django 4.2 on 2023-12-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicmodels', '0014_alter_vitals_diabetes_mellitus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitals',
            name='diabetes_mellitus',
            field=models.TextField(blank=True, default="Haven't Asked / Not Applicable", null=True),
        ),
    ]
